// <auto-generated />
namespace PrvaAplikacija.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DB_AUTH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB_AUTH));
        
        string IMigrationMetadata.Id
        {
            get { return "201704041650260_DB_AUTH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
