// <auto-generated />
namespace RetailApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_user_role : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_user_role));
        
        string IMigrationMetadata.Id
        {
            get { return "201704210020244_Add_user_role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
